### ISSUE TITLE
Windows Defender Virus Detected

### ISSUE THREAD

**Issue by Maxxxxxx-x** [pkulchenko/fullmoon#5]
Trojan:Script/Wacatac.B!ml was detected by windows defender

**Comment by pkulchenko** [comment]
Detected where? In the .lua code?

**Comment by jart** [comment]
If you're talking about the binaires at redbean.dev or justine.lol (which were audited and published by me) then it's a false positive. Virus scanners don't our open source project (https://github.com/jart/cosmopolitan/) and I don't know why, because we've made every effort to be maximally transparent. There's no telemetry. You can also audit the system calls of redbean using the `--strace` flag and see for yourself that it's behaving prim and proper. Furthermore, it works on six operating systems, including OpenBSD, which is the operating system that has the highest security requirements. If redbean is able to meet those requirements then that should give you a good idea of how committed we are to security. However there's little we can do about these black box unilateral virus scanner decisions.

**Comment by pkulchenko** [comment]
Thanks @jart!
